# 远程服务器链接，可以使用筛选参数。支持多种来源
server_url:
  - http://192.168.204.128:80/clash/proxies

clash_config_url:
  # - C:\Users\Windows10\.config\clash\profiles\1696516857345.yml

request:                        # default: http
domain:                         # default: 127.0.0.1
port: 81                        # default: 80
cron_interval: 30000            # default: 60 minutes
proxy_url: 
max_proxy_count:                # default: 50

healthcheck_timeout: 4          # default: 5
healthcheck_connection: 20      # default: 100

speedtest:                      # default: false
thirdpart_speedtest:            # default: false
speed_timeout: 5                # default 10
speed_connection: 4             # default 5
speed_download_size: 1024       # default 104857600
speed_sort: 2                   # 测速结果排序（0-节点名 1-带宽 2-延时） default 0
speed_server:                   # 测速地址 default https://speed.cloudflare.com/__down?bytes=%d
speed_min_bandwidth:            # 测速过滤最低带宽(B/s) default 1024
speed_max_ttfb:                 # 测速过滤最大延时(ms) default 4096

sleep_start: 23
sleep_end: 7
finish_cmd: 