# 远程服务器链接，可以使用筛选参数。支持多种来源
server_url:
  - http://192.168.254.128:80/clash/proxies

clash_config_url:
  # - C:\Users\Windows10\.config\clash\profiles\1696516857345.yml

request: http                   # 要显示到网页的协议 http / https
domain: 127.0.0.1               # 要显示到网页的域名 default: 127.0.0.1
port: 81                        # 要显示到网页上的端口 default: 80

cron_interval: 30000               # 工作间隔 default: 60  minutes

healthcheck_timeout: 4          # 单个节点健康检测时间限制，单位为秒。超过此时间限制的节点为无效节点 default 5
healthcheck_connection: 20      # 节点健康检测并发连接数。丢失大量可用节点时可大幅减少此项数值。 default 100

speedtest: false                 # 是否开启测速，默认关闭。开启测速会消耗大量流量 default false
speed_timeout: 5                # 单个节点测速时间限制，单位为秒。超过此时间限制的节点会测速失败 default 10
speed_connection: 4             # 测速并发连接数 default 5
speed_download_size: 1024           # 测速下载文件大小 default 104857600
speed_sort: 1                   # 测速结果排序（0-节点名 1-带宽 2-延时） default 0
speed_server:                   # 测速地址 default https://speed.cloudflare.com/__down?bytes=%d
speed_min_bandwidth:            # 测速过滤最低带宽(B/s) default 1024
speed_max_ttfb:                 # 测速过滤最大延时(ms) default 4096

sleep_start: 23
sleep_end: 7
finish_cmd: 